# This file was generated by GoReleaser. DO NOT EDIT.
cask "modelslab" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "debd3e0436d2f3ad0233e4a80814901593e5799435b818c5a816cbb177af2ef3"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ab02ea8f7920a6aff9f2bb70e7d5e4203960d1fbbc9c236f8f7e6f0b32c43840"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4793ae295d79b114d4926f8e1e4a84de4164781e53f52fe0d2d962bd95f1c8d8"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e9797131d9cd58a13cbd126d64a6dd74a6bc76959dc8d78f68b234bbddc339ad"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_linux_amd64.tar.gz"
    end
  end

  name "modelslab"
  desc "ModelsLab CLI — AI generation and account management from the terminal"
  homepage "https://modelslab.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modelslab"

  # No zap stanza required
end
