# This file was generated by GoReleaser. DO NOT EDIT.
cask "modelslab" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "bcf51e583770c0845a88a195e54c9f1a0d5effe402744a97530ce6fc7455dd4f"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "58850524a85b688386574ba2578c1116a230c37c2d52d8eb69db39162522c270"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "04d391ead15c50622bc6f18f86eae6338410566929a63f3db1470534312edc22"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "68ba59efc07d9bd83c901038d4e8452923d1dad1658c9341e33d8f22db4fa0a3"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_linux_amd64.tar.gz"
    end
  end

  name "modelslab"
  desc "ModelsLab CLI — AI generation and account management from the terminal"
  homepage "https://modelslab.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modelslab"

  # No zap stanza required
end
