# This file was generated by GoReleaser. DO NOT EDIT.
cask "modelslab" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "4d9ccee8c589bb1fd1418d3ed6a89837fa2ea5f03e2f8da36dabc5c89dcc0931"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d79c844d2bad3e472979344aa995d262bcfe8e684b9dff86a48c2933e6501ca"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e9af3938b8c86a700090ad59b413021ac8203372aededfa334c5a26248d24eb0"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "998a195dd0969c556bdcca9679b3570239c9a41085a923bdaa020a83c7cba714"
      url "https://github.com/ModelsLab/modelslab-cli/releases/download/v#{version}/modelslab_#{version}_linux_amd64.tar.gz"
    end
  end

  name "modelslab"
  desc "ModelsLab CLI — AI generation and account management from the terminal"
  homepage "https://modelslab.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modelslab"

  # No zap stanza required
end
